server:
  port: 21096
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: root
    publisher-returns: true
    connection-timeout: 5000
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.0.80;DatabaseName=MsgInfo
    username: scuser
    password: Hyd123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 # 初始化大小
      min-idle: 5 # 最小
      max-active: 100 # 最大
      max-wait: 60000 # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      test-while-idle: true # 当连接空闲时，是否执行连接测试
      test-on-borrow: false # 当从连接池借用连接时，是否测试该连接
      test-on-return: false # 在连接归还到连接池时是否测试该连接
      filters: config,wall,stat # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.slowSqlMillis=10;druid.stat.mergeSql=true;druid.stat.logSlowSql=false;config.decrypt=false
      # 合并多个DruidDataSource的监控数据
      #use-global-data-source-stat: true
      #WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true #是否启用StatFilter默认值true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      #StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet默认值true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin

mybatis:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

config:
  cleanHistoryFile: true #true 清理历史数据; false 不清理
  clearNum: 100
  MsgOverviewUrl: http://localhost:21091/GetMsgOverview  #10.92.0.77

  rabbit:
    xmlWriteBack: SC_XmlFile_WriteBack_Test

  filePath:
    build: D:\mq\exchange\01build
    sending: D:\mq\exchange\02sending
    waiting: D:\mq\exchange\03waiting
    receive: D:\mq\exchange\04received
    done: D:\mq\exchange\05done
    messageView: D:\mq\exchange\MessageView
